### ISSUE TITLE
TMethod>>#isAbstract behavior changed in Moose 8

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/Famix#70] opened 2020-07-06 12:02 UTC
Following the change explained in: https://github.com/moosetechnology/Famix/issues/69

The new #isAbstract introduced on FamixTMethod instead of the one from FamixTHasModifiers behave in a different way. Before, isAbstract was always returning a boolean. Now, it can also return nil. 

IMO it's a regression. We don't want to manage nils everywhere.

**Comment by ClotildeToullec** [comment] 2021-01-04 16:38
#isAbstract was changed in a88ab212ddc54e8b18fcf4d06c6bb1498bf18c83. 
However, this possibility to return nil was not addressed.

**Comment by ClotildeToullec** [comment] 2021-01-29 12:25
Related to https://github.com/moosetechnology/Fame/issues/18

**Comment by NicolasAnquetil** [comment] 2021-02-28 10:14
see #228 and declare #isAbstract as false by default

**Comment by NicolasAnquetil** [comment] 2021-02-28 10:16
see also #241

**Comment by anneetien** [comment] 2023-01-18 16:32
Do we still need to do something? @ClotildeToullec @NicolasAnquetil

**Comment by NicolasAnquetil** [comment] 2023-01-19 09:11
seems still valid to me

**Comment by anneetien** [comment] 2023-02-09 14:16
The same occurs for classes

**Comment by guillep** [comment] 2024-05-31 08:00
Hi, I'm new to moose, I'd like to help with this issue, but there is no clear way on how to reproduce it. Is there an example somewhere?

**Comment by guillep** [comment] 2024-05-31 08:14
As discussed with @NicolasAnquetil and @anneetien, we with @ISayarLu propose to close the issue.
We couldn't reproduce it in the latest version with a Smalltalk or a Java model.

If the issue is still there, it would be nice to reopen it with clear instructions to reproduce it.

**Closed by guillep** 2024-05-31 08:14 UTC
Labels: bug
